import Head from 'next/head'
import { Button } from 'ui'
export default function Home() {
  return (
    <>
      <Head>
        <title>Admins-Course-Marketplace</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    Welcome to Admin Front end
    <Button/>
    </>
  )
}
